// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCYNDIV4NE-yCpk5ZbfeVDrCuWAc2GFCU',
    appId: '1:704964874988:web:709cccae56ca1a686e0bc9',
    messagingSenderId: '704964874988',
    projectId: 'tap-in-22765',
    authDomain: 'tap-in-22765.firebaseapp.com',
    storageBucket: 'tap-in-22765.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5PCDen4keqiiRNkz5tG6QxzfJce0TI3U',
    appId: '1:704964874988:android:1136e8c9b158fc026e0bc9',
    messagingSenderId: '704964874988',
    projectId: 'tap-in-22765',
    storageBucket: 'tap-in-22765.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT5bg8CMu4iK2W27PZwCeJQVxHPyXtDqc',
    appId: '1:704964874988:ios:359c4db5843a44fb6e0bc9',
    messagingSenderId: '704964874988',
    projectId: 'tap-in-22765',
    storageBucket: 'tap-in-22765.firebasestorage.app',
    iosBundleId: 'com.example.tapIn',
  );
}
